### ISSUE TITLE
可以请教个问题吗？

### ISSUE THREAD

**Issue by merrily01** [albertchendao/demos#1]
目录结构：
bin
conf
XXX.jar
在bin目录下，想用java -jar XXX.jar -Dstaticdir=XXX   去设置-Dstaticdir为conf目录下的配置文件，使用的命令是： java -jar ../XXX.jar 8888 -Dstaticdir=../conf/
为什么conf下配置文件没生效呢？

**Comment by albertchendao** [comment]
使用绝对路径吧，-D 的参数会读取到系统中，变成 staticdir = "../conf/", 然后拼接到你使用 staticdir 的地方，相对路径就会变成基于你拼接的路径了。
